version: '3.8'

services:
  # Spring Boot Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: "http://proxy.th-wildau.de:8080"
        https_proxy: "http://proxy.th-wildau.de:8080"
        no_proxy: "localhost,127.0.0.1,.th-wildau.de"
    ports:
      - "8080:8080" # Zugriff auf die Anwendung unter http://localhost:8080
    environment:
      HTTP_PROXY: "http://proxy.th-wildau.de:8080"
      HTTPS_PROXY: "http://proxy.th-wildau.de:8080"
      NO_PROXY: "localhost,127.0.0.1,.th-wildau.de"
    depends_on:
      - mariadb
    networks:
      - app-network

  # MariaDB Service
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  # phpMyAdmin für Datenbankverwaltung
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: todo_user
      PMA_PASSWORD: todo_pass
    ports:
      - "8081:80" # Zugriff über http://localhost:8081
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
